const vdjscript_list =
{
    "VdjBuild": "8709",
    "Items":
    {
        "flow":
        {
            "down": "execute different actions depending if the key if pressed or released: 'down ? action1 : action2'",
            "isrepeat": "execute different actions depending if the key is being repeated or if it's the first message (on Windows, keyboard shortcuts are usually auto-repeated while held down): 'isrepeat ? nothing : goto_cue')",
            "nothing": "Do nothing.",
            "up": "execute different actions depending if the key if pressed or released: 'up ? action1 : action2'"
        },
        "param":
        {
            "blink": "turn on and off the LED, once per second.You can specify the speed: 'blink 1000ms' Speed can also be specified in number of beats: 'blink 1bt'.The time blinking can also be specified: 'blink 1bt 25%'",
            "color": "color 'red' color \"#C08040\n color 0.8 0.5 0.25 color 75% 'red' (returns a dimmed red) color 0.66 (returns a gray)",
            "color_mix": "Mix two colors based on an action in the third parameter color_mix white red `get_limiter`",
            "constant": "Return the specified value Example: 'get constant 75%' always returns 75%\n\n-----Alias-----\nget_constant",
            "dim": "equivalent of \"constant 0.1\"",
            "fadeout": "'loop & fadeout 10000ms 3000ms' will return 100 % when loop is on, and fade out to 0% after 10 seconds in 3 seconds when loop turns off Alternatively, the action can be entered as the third parameter in backticks: 'fadeout 10000ms 3000ms `loop`'",
            "false": "returns false\n\n-----Alias-----\nno\noff",
            "param_1_x": "invert the value of the calling slider/encoder/button (calculate 1/x) 'param_1_x & effect slider'",
            "param_add": "add the given value to the value of the calling slider/ encoder / button add the value of the first parameter with the value of the second parameter.Both parameters can be actions instead of values: 'param_add `get_var a` `get_var b`'",
            "param_bigger": "check if the value of the calling slider/encoder/button is bigger than something: 'param_bigger 0 ? sampler loop 200% : sampler loop 50%' compare value of the first parameter with the value of the second parameter. Both parameters can be actions instead of values: 'param_bigger pitch pitch_slider'\n\n-----Alias-----\nparam_greater",
            "param_cast": "cast the value of the previous query action into a new type: 'pitch_range & param_cast \"percentage\"'. Valid types are 'integer', 'float', 'percentage', 'ms', 'boolean', 'beats', 'text'. casting to text can also optionally limit the number of characters: 'get_browsed_song \"artist\" & param_cast \"text\" 5' to format a number as text with a specific number of digits: 'get_bpm & param_cast \"000\"' param_cast 'int_trunc' : provides the integer part of a number without rounding to the nearest integer param_cast 'frac' : provides the decimal part of a number. param_cast 'relative' and param_cast 'absolute' : change the parameter to be a relative or absolute value",
            "param_contains": "Check if the value of the calling action contains the string in the parameter.",
            "param_delta": "transform an absolute value into relative (example: 0.5, 0.7, 0.8 will become +0.0, +0.2, +0.1)",
            "param_equal": "Check if the value of the calling slider/encoder/button is equal to something To compare a string with the result of an action, use param_equal `action param` \"string\". For example: param_equal `get_browsed_song 'type'` \"audio\"",
            "param_invert": "invert the value of the calling slider/encoder/button (1-x): 'param_invert & pitch_slider'",
            "param_lowercase": "change the text result of the previous element in the script into lowercase",
            "param_make_discrete": "useful for smooth endless encoders, to make them discrete Example: 'param_make_discrete 0.1 & param_bigger 0 ? loop_move +100% : param_smaller 0 ? loop_move - 100%'",
            "param_mod": "wrap the value of the calling slider/encoder if more than the given value",
            "param_multiply": "multiply the value of the calling slider/encoder/button by the given value: 'param_multiply 300% & effect slider' The parameter can also be an action 'cue_pos 0 & param_multiply \"get_time total 1000\"'",
            "param_pingpong": "transform the value of the calling slider/encoder from a linear scale to a forth-and-back scale",
            "param_pow": "param_pow y : computes the power of the caller to the power of y. Can be 0.5 for calculating square root.",
            "param_smaller": "check if the value of the calling slider/encoder/button is smaller than something: 'param_smaller 0 ? sampler loop 200% : sampler loop 50%'",
            "param_ucfirst": "change the first letter into upper case and the rest in lower case",
            "param_uppercase": "change the text result of the previous element in the script into uppercase",
            "pulse": "return true when the previous action turns to true only for the duration specified: 'is_using 'equalizer' & pulse 2000ms'",
            "true": "returns true\n\n-----Alias-----\non\nyes"
        },
        "repeat":
        {
            "doubleclick": "execute different actions depending if the key is pressed twice in a short period of time or not: 'doubleclick ? automix : mix_now'. you can specify the time between two presses ('doubleclick 1000ms'), by default it's 300ms.",
            "holding": "execute different actions depending if the key is pressed for a long time or not: 'holding ? automix : mix_now'. you can specify the time ('holding 1000ms'), by default it's 500ms.",
            "repeat": "repeat the actions every x ms as long as the key is pressed: 'repeat 1000ms & browser_scroll +1' (default is 500ms if no speed is specified. Second parameter can specify a delay before repeating the first time)",
            "repeat_start": "Repeat an action at a specified interval: 'repeat_start 'myrepeatname' 1000ms 5 & browser_scroll +1' (first parameter is an identifier name, second parameter is the interval and the third optional parameter can specify a number of times to repeat). The first action will be performed after an interval has passed. The interval can be specified in milliseconds, beats, or can be an action of itself. 'repeat_start 'myrepeatname' 1bt' or 'repeat_start 'myrepeatname `get_var a`'",
            "repeat_start_instant": "Repeat an action at a specified interval: 'repeat_start_instant 'myrepeatname' 1000ms 5 & browser_scroll +1' (first parameter is an identifier name, second parameter is the interval and the third optional parameter can specify a number of times to repeat). The first action will be performed immediately.",
            "repeat_stop": "stop a previous repeat_start or repeat_start_instant action: 'repeat_stop 'myrepeatname''",
            "wait": "wait for the specified amount of time between two script actions: 'wait 1bt & pause', 'wait 500ms & play'"
        },
        "skin":
        {
            "custom_button": "a custom button is a button with initially no action, but the action can be written in VDJScript by the user",
            "custom_button_edit": "open the custom button editor to set or change the action",
            "custom_button_name": "return (or set) the name for this custom button",
            "get_skin_color": "TODO",
            "has_cover": "TODO",
            "has_custom_button": "returns true if this custom button has an action assigned to it",
            "has_logo": "TODO",
            "is_using": "check if a particular feature is being used('filter', 'equalizer', 'loop', 'cue', 'sample', 'pads', 'effect', 'load') ",
            "load_skin": "load a new skin. Use syntax \" load_skin ':newvariation' \" to load a different variation inside the same skin file.",
            "lock_panel": "NOTE: despite the name, this action acts on <split> elements, not <panel>\n\n-----Alias-----\nlock_pannel",
            "multibutton": "Click on the named multibutton: 'multibutton \"my_button\"'",
            "multibutton_select": "Open the selection menu for the named multibutton. If a second text parameter is provided after the name, use it as the new action to load in the multibutton: 'multibutton_select \"my_button\" \"goto_cue 2 & play\"'",
            "rack": "Open/close a unit in specified rack. Example: \"rack 'rack1' 'unit1'\"",
            "rack_prioritize": "Prioritizes a unit of the specified rack. When more configurations with same size are available, the prioritized unit will get most space. Example: \"rack_prioritize 'rack1' 'unit1'\"",
            "rack_solo": "Open/close a unit in full size on the specified rack. Closing the unit will re-open the previous configuration. Example: \"rack_solo 'rack1' 'unit1'\"",
            "show_splitpanel": "Show/hide the specified split panel Examples: \"show_splitpanel 'sidelist'\", \"show_splitpanel 'sideview' on\", \"show_splitpanel 'sidelist' 50 %\"",
            "skin_empty_buttons": "TODO",
            "skin_height": "TODO",
            "skin_panel": "show or hide a panel on the skin. \"skin_panel 'my_panel' on\"\n\n-----Alias-----\nskin_pannel",
            "skin_panelgroup": "change which panel from a skin panel group is shown. syntax \"skin_panelgroup 'groupname' 'panelname'\" or \"skin_panelgroup 'groupname' +1\" or \"skin_panelgroup 'groupname' 0.75\"\n\n-----Alias-----\nskin_pannelgroup",
            "skin_panelgroup_available": "set a panel to be available or not. panels that are not available will not show up in group cycles",
            "skin_starter_tip": "TODO",
            "skin_width": "TODO",
            "switch_skin_variation": "TODO",
            "zoom": "zoom horizontal rhythm and scratch visual\n\n-----Alias-----\nzoom_scratch",
            "zoom_vertical": "zoom vertical scratch wave"
        },
        "system":
        {
            "debug": "display the value of the parameter (you can use this to see what values controllers are sending, for example)",
            "get_battery": "returns how much battery is left on your laptop",
            "get_clock": "get the current time (use 'get_clock 12' to display AM/PM)",
            "get_cpu": "get the cpu activity",
            "get_date": "get the current date (use 'get_date \"format\"' to get the date in a specific format. format can include %Y, %m, %d for year, month and day, %A for weekday)",
            "get_peak_audio": "TODO",
            "getfood": "because no DJ should work on an empty stomach",
            "handshake": "Perform an encrypted handshake to ensure that this plugin is currently being called by a real VirtualDJ environment. Call this passing any string, decrypt the result using VirtualDJ's handshake public key, and check that it matches what you passed. See the developer documentation on our website for example code.",
            "has_battery": "returns true if your computer has batteries",
            "has_notch": "return true when the display has a notch at the top center and the skin is maximized, false otherwise",
            "has_system_volume": "Returns true when the system volume can be modified",
            "is_battery": "returns true if your computer is running on batteries",
            "is_mac": "return true if the computer is a MAC, false if it's a PC\n\n-----Alias-----\nis_macos",
            "is_pc": "return true if the computer is a PC, false if it's a MAC (example: <panel visible=\"is_pc\" />)\n\n-----Alias-----\nis_windows",
            "open_help": "open the user guide",
            "show_keyboard": "display an onscreen keyboard",
            "system": "TODO",
            "system_volume": "Change the system volume of the active sound card when available (use has_system_volume to check)"
        },
        "variables":
        {
            "controllervar": "TODO",
            "cycle": "TODO",
            "get_var": "TODO",
            "set": "TODO",
            "set_var": "TODO",
            "set_var_dialog": "TODO",
            "toggle": "TODO",
            "var": "TODO",
            "var_equal": "TODO",
            "var_greater": "TODO",
            "var_list": "TODO",
            "var_not_equal": "TODO",
            "var_smaller": "TODO"
        },
        "window":
        {
            "close": "TODO",
            "maximize": "TODO",
            "minimize": "TODO",
            "open_stem_creator": "TODO",
            "show_window": "TODO"
        },
        "audio":
        {
            "beat_juggle": "TODO",
            "beatjump": "TODO",
            "beatjump_pad": "TODO",
            "beatjump_page": "TODO",
            "beatjump_select": "TODO",
            "clone_deck": "TODO",
            "clone_from_deck": "TODO",
            "dualdeckmode": "TODO",
            "dualdeckmode_decks": "TODO",
            "dump": "TODO",
            "goto": "TODO",
            "goto_bar": "TODO",
            "goto_first_beat": "TODO",
            "goto_start": "TODO",
            "mixermode": "TODO",
            "move_deck": "TODO",
            "reverse": "TODO",
            "seek": "TODO",
            "song_pos": "TODO",
            "songpos_remain": "TODO",
            "songpos_warning": "TODO",
            "stems_split": "TODO",
            "stems_split_unlink": "TODO",
            "swap_decks": "TODO"
        },
        "audio_controls":
        {
            "auto_sync_options": "TODO",
            "blink_play": "TODO",
            "deck_options": "TODO",
            "emergency_play": "TODO",
            "pause": "TODO",
            "pause_stop": "TODO",
            "play": "TODO",
            "play_button": "TODO\n\n-----Alias-----\nplay_3button",
            "play_options": "TODO",
            "play_pause": "TODO",
            "play_stutter": "TODO",
            "stop": "TODO",
            "stop_button": "TODO\n\n-----Alias-----\nstop_3button"
        },
        "audio_inputs":
        {
            "aux_volume": "TODO",
            "djc_mic": "TODO",
            "linein": "TODO",
            "linein_rec": "TODO",
            "mic": "TODO\n\n-----Alias-----\nmicrophone",
            "mic_eq_high": "TODO",
            "mic_eq_low": "TODO",
            "mic_eq_mid": "TODO",
            "mic_rec": "TODO",
            "mic_talkover": "TODO"
        },
        "audio_scratch":
        {
            "get_scratch_direction": "TODO",
            "get_slip_active": "TODO",
            "get_slip_time": "TODO",
            "hold": "TODO\n\n-----Alias-----\nscratch_hold",
            "jogwheel": "TODO\n\n-----Alias-----\njog\njog_wheel",
            "motorwheel": "TODO",
            "nudge": "TODO",
            "scratch": "TODO",
            "scratch_dna": "TODO",
            "scratch_dna_editor": "TODO",
            "scratch_dna_option": "TODO",
            "slip": "TODO",
            "slip_mode": "TODO",
            "speedwheel": "TODO",
            "touchwheel": "TODO\n\n-----Alias-----\nscratch_wheel\n scratchwheel",
            "touchwheel_touch": "TODO\n\n-----Alias-----\nscratch_wheel_touch\nscratchwheel_touch\nspeedwheel_touch",
            "vinyl_mode": "TODO",
            "wheel_mode": "TODO"
        },
        "audio_volumes":
        {
            "auto_crossfade": "TODO\n\n-----Alias-----\nauto_crossfader",
            "booth_volume": "TODO",
            "colorfx_prefader": "TODO",
            "crossfader": "TODO\n\n-----Alias-----\ncrossfader_slider",
            "crossfader_curve": "TODO",
            "crossfader_disable": "TODO",
            "crossfader_hamster": "TODO",
            "fake_eq": "TODO",
            "fake_filter": "TODO",
            "fake_gain": "TODO",
            "fake_hp": "TODO",
            "fake_hpmix": "TODO",
            "fake_master": "TODO",
            "fake_mixer": "TODO",
            "fake_pfl": "TODO",
            "gain": "TODO\n\n-----Alias-----\ngain_slider\npower_gain",
            "gain_label": "TODO",
            "gain_relative": "TODO",
            "get_crossfader_result": "TODO",
            "get_level": "TODO",
            "get_level_left": "TODO",
            "get_level_left_peak": "TODO",
            "get_level_log": "TODO",
            "get_level_peak": "TODO",
            "get_level_right": "TODO",
            "get_level_right_peak": "TODO",
            "get_limiter": "TODO",
            "get_vu_meter": "TODO",
            "get_vu_meter_left": "TODO",
            "get_vu_meter_left_peak": "TODO",
            "get_vu_meter_peak": "TODO",
            "get_vu_meter_right": "TODO",
            "get_vu_meter_right_peak": "TODO",
            "headphone_crossfader": "TODO",
            "headphone_gain": "TODO",
            "headphone_mix": "TODO",
            "headphone_volume": "TODO",
            "is_audible": "TODO",
            "level": "TODO\n\n-----Alias-----\nlevel_slider\nvolume\nvolume_slider",
            "levelfader_curve": "TODO\n\n-----Alias-----\nfader_curve",
            "master_balance": "TODO",
            "master_volume": "TODO",
            "mic2_volume": "TODO",
            "mic_volume": "TODO",
            "mono_mix": "TODO",
            "mute": "TODO",
            "set_gain": "TODO"
        },
        "automix":
        {
            "automix": "TODO",
            "automix_add_next": "TODO",
            "automix_dualdeck": "TODO",
            "automix_editor": "TODO",
            "automix_editor_movetrack": "TODO",
            "automix_skip": "TODO",
            "create_list_from_playlist": "TODO\n\n-----Alias-----\ncreate_virtualfolder_from_playlist",
            "get_automix_position": "TODO",
            "get_automix_song": "TODO",
            "get_playlist_time": "TODO",
            "mix_and_load_next": "TODO",
            "mix_next": "TODO",
            "mix_next_sidelist": "TODO",
            "mix_now": "TODO",
            "mix_now_nosync": "TODO",
            "mix_selected": "TODO",
            "playlist_add": "TODO",
            "playlist_clear": "TODO",
            "playlist_load_and_keep": "TODO",
            "playlist_load_and_remove": "TODO",
            "playlist_options": "TODO",
            "playlist_randomize": "TODO",
            "playlist_randomize_once": "TODO",
            "playlist_remove_duplicates": "TODO",
            "playlist_remove_played": "TODO",
            "playlist_repeat": "TODO",
            "playlist_save": "TODO",
            "relay_play": "TODO",
            "sidelist_options": "TODO",
            "switch_sidelist_playlist": "TODO"
        },
        "browser":
        {
            "add_favoritefolder": "TODO",
            "add_filterfolder": "TODO",
            "add_list": "TODO\n\n-----Alias-----\nadd_virtualfolder",
            "add_to_list": "TODO\n\n-----Alias-----\nvirtualfolder_add",
            "browsed_file_analyze": "TODO",
            "browsed_file_color": "TODO",
            "browsed_file_info": "TODO",
            "browsed_file_prepare_stems": "TODO",
            "browsed_file_reload_tag": "TODO",
            "browsed_file_rename": "TODO",
            "browsed_file_reveal": "TODO",
            "browser_enter": "TODO",
            "browser_export": "TODO",
            "browser_folder": "TODO",
            "browser_geniusdj": "TODO",
            "browser_gotofolder": "TODO",
            "browser_isactive": "TODO",
            "browser_move": "TODO",
            "browser_open_folder": "TODO",
            "browser_options": "TODO",
            "browser_padding": "TODO",
            "browser_remove": "TODO",
            "browser_scroll": "TODO",
            "browser_shortcut": "TODO",
            "browser_sort": "TODO",
            "browser_window": "TODO",
            "browser_zoom": "TODO\n\n-----Alias-----\nbrowser",
            "clear_search": "TODO",
            "edit_comment": "TODO",
            "edit_search": "TODO",
            "edit_singer": "TODO",
            "file_count": "TODO",
            "file_info": "TODO",
            "font_size": "TODO",
            "goto_last_folder": "TODO",
            "grid_view": "TODO",
            "has_linked_tracks": "TODO",
            "has_quick_filter": "TODO",
            "info_options": "TODO\n\n-----Alias-----\ninfos_options",
            "karaoke_add": "TODO",
            "karaoke_load": "TODO",
            "load": "TODO",
            "load_deck_set": "TODO",
            "load_next": "TODO",
            "load_previous": "TODO",
            "load_pulse": "TODO",
            "load_pulse_active": "TODO",
            "loaded": "TODO",
            "log_search": "TODO",
            "mark_linked_tracks": "TODO\n\n-----Alias-----\nmark_related_tracks",
            "not_played": "TODO",
            "page": "TODO",
            "playlist_load": "TODO",
            "quick_filter": "TODO",
            "rating": "TODO",
            "recurse_folder": "TODO",
            "save_deck_set": "TODO",
            "search": "TODO",
            "search_add": "TODO",
            "search_delete": "TODO",
            "search_folder": "TODO",
            "search_options": "TODO",
            "search_playlists": "TODO",
            "set_browsed_file_bpm": "TODO",
            "sidelist_add": "TODO",
            "sidelist_clear": "TODO",
            "sidelist_load": "TODO",
            "sidelist_load_and_keep": "TODO",
            "sidelist_load_and_remove": "TODO",
            "sidereco_options": "TODO",
            "sidereco_song": "TODO",
            "sidereco_source": "TODO",
            "sideview": "TODO",
            "sideview_options": "TODO",
            "sideview_sort": "TODO",
            "sideview_title": "TODO",
            "sideview_triggerpad": "TODO",
            "undo_load": "TODO",
            "unload": "TODO",
            "view_options": "TODO"
        },
        "config":
        {
            "apply_audio_config": "TODO",
            "auto_cue": "TODO",
            "auto_match_bpm": "TODO",
            "auto_match_key": "TODO",
            "auto_pitch_lock": "TODO",
            "connect": "TODO",
            "eventscheduler": "TODO",
            "eventscheduler_start": "TODO",
            "fader_start": "TODO",
            "get_lemode": "TODO",
            "play_mode": "TODO",
            "quantize_loop": "TODO",
            "quantize_setcue": "TODO",
            "save_config": "TODO\n\n-----Alias-----\nsaveregistryconfig",
            "setting": "TODO",
            "setting_ismodified": "TODO",
            "setting_reset": "TODO",
            "setting_setdefault": "TODO",
            "setting_setsession": "TODO",
            "setting_setsession_deck": "TODO",
            "settings": "TODO\n\n-----Alias-----\nconfig",
            "smart_cue": "TODO",
            "smart_loop": "TODO",
            "smart_play": "TODO\n\n-----Alias-----\nauto_sync",
            "smart_scratch": "TODO"
        },
        "controllers":
        {
            "action_deck": "TODO",
            "assign_controller": "TODO",
            "controller_battery": "TODO",
            "controller_mapping": "TODO",
            "controllerscreen_deck": "TODO",
            "denon_platter": "TODO",
            "device_side": "TODO",
            "display_time": "TODO",
            "djc_button": "TODO",
            "djc_button_popup": "TODO",
            "djc_button_select": "TODO",
            "djc_button_slider": "TODO",
            "djc_panel": "TODO",
            "djc_shift": "TODO",
            "effect_fxsendreturndeck": "TODO",
            "effect_fxsendreturndeck_multi": "TODO",
            "effect_fxsendreturnenable": "TODO",
            "gemini_waveform_zoomlevel": "TODO",
            "get_controller_image": "TODO",
            "get_controller_name": "TODO",
            "get_controller_screen": "TODO",
            "get_denon_cuepoints": "TODO",
            "get_denon_platter": "TODO",
            "get_display": "TODO",
            "get_gemini_display": "TODO",
            "get_gemini_waveform": "TODO",
            "get_ns7_platter": "TODO",
            "get_numark_beatgrid": "TODO",
            "get_numark_songpos": "TODO",
            "get_numark_waveform": "TODO",
            "get_pioneer_display": "TODO",
            "get_pioneer_loop_display": "TODO",
            "get_rotation_cue": "TODO",
            "get_rotation_slip": "TODO",
            "invert_controllers": "TODO",
            "keyboard_shortcuts": "TODO",
            "menu": "TODO",
            "menu_button": "TODO",
            "menu_cycledisplay": "TODO",
            "midiclock_active": "TODO",
            "miditovst_active": "TODO",
            "mixer_order": "TODO",
            "motor_switch": "TODO",
            "motorwheel_instant_play": "TODO",
            "ns7_platter": "TODO",
            "numark_waveform_zoom": "TODO",
            "os2l_button": "TODO",
            "os2l_cmd": "TODO",
            "os2l_info": "TODO",
            "os2l_scene": "TODO",
            "phase_movement": "TODO",
            "phase_position": "TODO",
            "pioneer_cue": "TODO",
            "pioneer_play": "TODO",
            "refresh_controller": "TODO",
            "reinit_controller": "TODO",
            "rescan_controllers": "TODO",
            "rzx_touch": "TODO",
            "rzx_touch_x": "TODO",
            "rzx_touch_y": "TODO",
            "select_master_output": "TODO",
            "set_deck": "TODO",
            "shift": "TODO",
            "show_text": "TODO",
            "v7_status": "TODO"
        },
        "cues":
        {
            "cue": "TODO",
            "cue_action": "TODO",
            "cue_button": "TODO\n\n-----Alias-----\ncue_3button",
            "cue_color": "TODO",
            "cue_countdown": "TODO",
            "cue_counter": "TODO",
            "cue_countup": "TODO",
            "cue_cup": "TODO",
            "cue_display": "TODO",
            "cue_loop": "TODO",
            "cue_loop_autosync": "TODO",
            "cue_loop_hold": "TODO",
            "cue_name": "TODO",
            "cue_play": "TODO",
            "cue_pos": "TODO",
            "cue_select": "TODO",
            "cue_stop": "TODO",
            "cues_options": "TODO",
            "delete_cue": "TODO",
            "get_cue": "TODO",
            "goto_cue": "TODO",
            "has_cue": "TODO",
            "hot_cue": "TODO\n\n-----Alias-----\nhotcue",
            "lock_cues": "TODO",
            "set_cue": "TODO",
            "shift_all_cues": "TODO",
            "silent_cue": "TODO",
            "sort_cues": "TODO"
        },
        "deck_select":
        {
            "cross_assign": "TODO",
            "get_deck_color": "TODO",
            "invert_deck": "TODO",
            "leftcross": "TODO",
            "leftdeck": "TODO",
            "masterdeck": "TODO",
            "masterdeck_auto": "TODO",
            "pfl": "TODO",
            "rightcross": "TODO",
            "rightdeck": "TODO",
            "select": "TODO"
        },
        "equalizer":
        {
            "eq_crossfader_high": "TODO",
            "eq_crossfader_low": "TODO",
            "eq_crossfader_mid": "TODO\n\n-----Alias-----\neq_crossfader_med",
            "eq_high": "TODO\n\n-----Alias-----\neq_high_slider",
            "eq_high_freq": "TODO",
            "eq_kill_high": "TODO",
            "eq_kill_low": "TODO",
            "eq_kill_mid": "TODO\n\n-----Alias-----\neq_kill_med",
            "eq_low": "TODO\n\n-----Alias-----\neq_low_slider",
            "eq_low_freq": "TODO",
            "eq_mid": "TODO\n\n-----Alias-----\neq_med\neq_mid_slider",
            "eq_mid_freq": "TODO",
            "eq_mode": "TODO",
            "eq_reset": "TODO",
            "filter": "TODO\n\n-----Alias-----\nfilter_slider",
            "filter_activate": "TODO",
            "filter_label": "TODO",
            "filter_resonance": "TODO",
            "filter_selectcolorfx": "TODO",
            "has_stems": "TODO",
            "high_label": "TODO",
            "low_label": "TODO",
            "mid_label": "TODO",
            "mute_stem": "TODO",
            "only_stem": "TODO",
            "stem": "TODO",
            "stem_color": "TODO",
            "stem_pad": "TODO",
            "stems_bleed": "TODO"
        },
        "get":
        {
            "browsed_song": "TODO",
            "browsed_song_hashtag": "TODO",
            "get_activedeck": "TODO",
            "get_album": "TODO",
            "get_arm": "TODO",
            "get_artist": "TODO",
            "get_artist_before_feat": "TODO",
            "get_artist_title": "TODO",
            "get_artist_title_separator": "TODO",
            "get_askthedj": "TODO",
            "get_askthedj_unread": "TODO",
            "get_automix": "TODO",
            "get_bar": "TODO",
            "get_beat": "TODO",
            "get_beat2": "TODO",
            "get_beat_bar": "TODO",
            "get_beat_counter": "TODO",
            "get_beat_num": "TODO",
            "get_beatdiff": "TODO",
            "get_beatgrid": "TODO",
            "get_beatpos": "TODO",
            "get_bpm": "TODO",
            "get_browsed_album": "TODO",
            "get_browsed_artist": "TODO",
            "get_browsed_artist_title": "TODO",
            "get_browsed_bpm": "TODO",
            "get_browsed_color": "TODO",
            "get_browsed_comment": "TODO",
            "get_browsed_composer": "TODO",
            "get_browsed_filepath": "TODO",
            "get_browsed_folder": "TODO",
            "get_browsed_folder_icon": "TODO",
            "get_browsed_folder_path": "TODO",
            "get_browsed_folder_scrollpos": "TODO",
            "get_browsed_folder_scrollsize": "TODO",
            "get_browsed_folder_selection_index": "TODO",
            "get_browsed_folder_tab": "TODO",
            "get_browsed_genre": "TODO",
            "get_browsed_header": "TODO",
            "get_browsed_key": "TODO",
            "get_browsed_scrollpos": "TODO",
            "get_browsed_scrollsize": "TODO",
            "get_browsed_selection_index": "TODO",
            "get_browsed_song": "TODO",
            "get_browsed_title": "TODO",
            "get_browsed_title_artist": "TODO",
            "get_build": "TODO",
            "get_comment": "TODO",
            "get_composer": "TODO",
            "get_custom_text": "TODO",
            "get_deck": "TODO",
            "get_deck_analysis": "TODO",
            "get_deck_letter": "TODO",
            "get_decks": "TODO",
            "get_defaultdeck": "TODO",
            "get_featuring_after_artist": "TODO",
            "get_filename": "TODO",
            "get_filepath": "TODO",
            "get_filesize": "TODO",
            "get_firstbeat": "TODO",
            "get_firstbeat_local": "TODO",
            "get_genre": "TODO",
            "get_hasheadphones": "TODO\n\n-----Alias-----\nget_hasheadphone",
            "get_hasinput": "TODO",
            "get_haslinein": "TODO",
            "get_hasmaster": "TODO",
            "get_hasmic": "TODO",
            "get_hwnd": "TODO",
            "get_leftdeck": "TODO",
            "get_license": "TODO",
            "get_loaded_song": "TODO",
            "get_loaded_song_color": "TODO",
            "get_membership": "TODO",
            "get_phrase_num": "TODO",
            "get_plugindeck": "TODO",
            "get_position": "TODO",
            "get_record_message": "TODO",
            "get_record_min": "TODO",
            "get_record_ms": "TODO",
            "get_record_msf": "TODO",
            "get_record_sec": "TODO",
            "get_record_size": "TODO",
            "get_record_time": "TODO",
            "get_remix_after_title": "TODO",
            "get_rightdeck": "TODO",
            "get_rotation": "TODO",
            "get_song_event": "TODO",
            "get_songlength": "TODO",
            "get_spectrum_band": "TODO",
            "get_time": "TODO",
            "get_time_hour": "TODO",
            "get_time_min": "TODO",
            "get_time_ms": "TODO",
            "get_time_msf": "TODO",
            "get_time_sec": "TODO",
            "get_time_sign": "TODO",
            "get_title": "TODO",
            "get_title_artist": "TODO",
            "get_title_before_remix": "TODO",
            "get_title_remix": "TODO",
            "get_totaltime_min": "TODO",
            "get_totaltime_ms": "TODO",
            "get_totaltime_msf": "TODO",
            "get_totaltime_sec": "TODO",
            "get_username": "TODO",
            "get_vdj_folder": "TODO",
            "get_version": "TODO",
            "get_volume": "TODO",
            "get_year": "TODO",
            "has_aux": "TODO",
            "loaded_song": "TODO",
            "loaded_song_hashtag": "TODO",
            "prelisten_info": "TODO"
        },
        "karaoke":
        {
            "get_karaoke_background_song": "TODO",
            "get_next_karaoke_song": "TODO",
            "has_karaoke_next": "TODO",
            "is_karaoke_idle": "TODO",
            "is_karaoke_playing": "TODO",
            "karaoke": "TODO",
            "karaoke_options": "TODO",
            "karaoke_show": "TODO",
            "karaoke_venue_name": "TODO"
        },
        "key":
        {
            "get_harmonic": "TODO",
            "get_key": "TODO",
            "get_key_color": "TODO",
            "get_key_modifier": "TODO",
            "get_key_modifier_text": "TODO",
            "key": "TODO",
            "key_lock": "TODO\n\n-----Alias-----\nkeylock",
            "key_match_button": "TODO",
            "key_match_menu": "TODO",
            "key_move": "TODO",
            "key_smooth": "TODO",
            "keycue_pad": "TODO",
            "keycue_pad_color": "TODO",
            "keycue_pad_jump": "TODO",
            "keycue_pad_page": "TODO",
            "match_key": "TODO",
            "set_key": "TODO"
        },
        "loop":
        {
            "get_active_loop": "TODO",
            "get_loop": "TODO",
            "get_loop_in_time": "TODO",
            "get_loop_out_time": "TODO",
            "get_saved_loop": "TODO",
            "loop": "TODO",
            "loop_adjust": "TODO",
            "loop_back": "TODO",
            "loop_button": "TODO",
            "loop_color": "TODO",
            "loop_delete": "TODO",
            "loop_double": "TODO",
            "loop_exit": "TODO",
            "loop_half": "TODO",
            "loop_in": "TODO",
            "loop_length": "TODO",
            "loop_load": "TODO",
            "loop_load_prepare": "TODO",
            "loop_move": "TODO",
            "loop_options": "TODO",
            "loop_out": "TODO",
            "loop_pad": "TODO",
            "loop_pad_mode": "TODO",
            "loop_pad_page": "TODO",
            "loop_position": "TODO",
            "loop_roll": "TODO",
            "loop_roll_mode": "TODO",
            "loop_save": "TODO",
            "loop_select": "TODO",
            "pioneer_loop": "TODO",
            "pioneer_loop_in": "TODO",
            "pioneer_loop_out": "TODO",
            "reloop": "TODO",
            "reloop_exit": "TODO",
            "repeat_song": "TODO",
            "saved_loop": "TODO",
            "saved_loop_autotrigger": "TODO",
            "saved_loop_display": "TODO",
            "saved_loop_prepare": "TODO",
            "slicer": "TODO"
        },
        "macro":
        {
            "macro_play": "TODO",
            "macro_record": "TODO"
        },
        "pads":
        {
            "pad": "TODO",
            "pad_bank2": "TODO",
            "pad_button_color": "TODO",
            "pad_color": "TODO",
            "pad_edit": "TODO",
            "pad_has_16pads": "TODO",
            "pad_has_action": "TODO",
            "pad_has_color": "TODO",
            "pad_has_menu": "TODO",
            "pad_has_param": "TODO",
            "pad_has_pressure": "TODO",
            "pad_menu": "TODO",
            "pad_page": "TODO\n\n-----Alias-----\npad_pages",
            "pad_page_select": "TODO\n\n-----Alias-----\npad_page_favorite_select",
            "pad_param": "TODO",
            "pad_param2": "TODO",
            "pad_param_visible": "TODO",
            "pad_pressure": "TODO",
            "pad_pushed": "TODO",
            "padfx": "TODO",
            "padfx_single": "TODO",
            "padshift": "TODO",
            "padshift_button_color": "TODO",
            "padshift_pressure": "TODO"
        },
        "pitch":
        {
            "backspin": "TODO",
            "brakespeed": "TODO",
            "get_pitch": "TODO",
            "get_pitch_value": "TODO",
            "get_pitch_zero": "TODO",
            "master_tempo": "TODO",
            "pitch": "TODO\n\n-----Alias-----\npitch2\npitch2_slider\npitch_slider",
            "pitch_bend": "TODO",
            "pitch_lock": "TODO\n\n-----Alias-----\npitchlock",
            "pitch_motorized": "TODO",
            "pitch_range": "TODO",
            "pitch_relative": "TODO",
            "pitch_reset": "TODO",
            "pitch_zero": "TODO",
            "startupspeed": "TODO"
        },
        "plugins":
        {
            "effect_3slots_layout": "TODO",
            "effect_active": "TODO\n\n-----Alias-----\neffect_activate",
            "effect_arm_active": "TODO",
            "effect_arm_beats": "TODO",
            "effect_arm_bpm": "TODO",
            "effect_arm_deck": "TODO",
            "effect_arm_select": "TODO",
            "effect_arm_slider": "TODO",
            "effect_arm_slider_label": "TODO",
            "effect_arm_slider_name": "TODO",
            "effect_arm_slider_text": "TODO",
            "effect_arm_slot": "TODO",
            "effect_arm_stem": "TODO",
            "effect_bank_load": "TODO",
            "effect_bank_save": "TODO",
            "effect_beats": "TODO",
            "effect_beats_all": "TODO",
            "effect_bpm_deck": "TODO",
            "effect_bpm_deck_tap": "TODO",
            "effect_button": "TODO",
            "effect_clone": "TODO",
            "effect_colorfx": "TODO",
            "effect_colorslider": "TODO",
            "effect_command": "TODO",
            "effect_disable_all": "TODO",
            "effect_dock_gui": "TODO",
            "effect_has_beats": "TODO",
            "effect_has_button": "TODO",
            "effect_has_length": "TODO",
            "effect_has_slider": "TODO",
            "effect_mixfx": "TODO",
            "effect_mixfx_activate": "TODO",
            "effect_mixfx_select": "TODO",
            "effect_releaseslider": "TODO",
            "effect_releaseslider_active": "TODO",
            "effect_select": "TODO",
            "effect_select_multi": "TODO",
            "effect_select_popup": "TODO",
            "effect_select_toggle": "TODO",
            "effect_show_gui": "TODO",
            "effect_slider": "TODO\n\n-----Alias-----\neffect_slider_slider",
            "effect_slider_active": "TODO\n\n-----Alias-----\neffect_slider_activate",
            "effect_slider_reset": "TODO",
            "effect_slider_skip_length": "TODO",
            "effect_stems": "TODO",
            "effect_stems_color": "TODO",
            "effects_used": "TODO",
            "get_effect_button_count": "TODO",
            "get_effect_button_name": "TODO",
            "get_effect_button_shortname": "TODO",
            "get_effect_name": "TODO",
            "get_effect_slider_count": "TODO",
            "get_effect_slider_default": "TODO",
            "get_effect_slider_label": "TODO",
            "get_effect_slider_label_full": "TODO",
            "get_effect_slider_name": "TODO",
            "get_effect_slider_shortname": "TODO",
            "get_effect_slider_text": "TODO",
            "get_effect_string": "TODO\n\n-----Alias-----\neffect_string",
            "get_effect_string_name": "TODO",
            "get_effect_title": "TODO",
            "get_effects_used": "TODO",
            "get_nb_multicam": "TODO",
            "get_video_fx_slider_label": "TODO",
            "get_videofx_name": "TODO",
            "get_videotrans_name": "TODO",
            "is_releasefx": "TODO",
            "pluginsongpos": "TODO",
            "show_pluginpage": "TODO",
            "video_fx": "TODO",
            "video_fx_button": "TODO",
            "video_fx_clear": "TODO",
            "video_fx_select": "TODO",
            "video_fx_slider": "TODO\n\n-----Alias-----\nvideo_fx_slider_slider",
            "video_source": "TODO",
            "video_source_select": "TODO",
            "video_transition_button": "TODO",
            "video_transition_select": "TODO",
            "video_transition_slider": "TODO\n\n-----Alias-----\nvideo_transition_slider_slider"
        },
        "poi":
        {
            "adjust_cbg": "TODO",
            "beat_tap": "TODO",
            "edit_bpm": "TODO",
            "edit_poi": "TODO",
            "goto_mixpoint": "TODO",
            "reanalyze": "TODO",
            "set_bpm": "TODO",
            "set_firstbeat": "TODO",
            "set_loadpoint": "TODO",
            "set_mixpoint": "TODO"
        },
        "prelisten":
        {
            "prelisten": "TODO\n\n-----Alias-----\npreview",
            "prelisten_options": "TODO",
            "prelisten_output": "TODO",
            "prelisten_pos": "TODO",
            "prelisten_stop": "TODO"
        },
        "record":
        {
            "broadcast": "TODO",
            "broadcast_message": "TODO",
            "record": "TODO",
            "record_config": "TODO",
            "record_cut": "TODO",
            "record_vu": "TODO"
        },
        "sampler":
        {
            "get_sample_color": "TODO",
            "get_sample_info": "TODO",
            "get_sample_name": "TODO\n\n-----Alias-----\nget_sample_slot_name",
            "get_sampler_bank": "TODO",
            "get_sampler_bank_count": "TODO",
            "get_sampler_bank_id": "TODO",
            "get_sampler_count": "TODO",
            "get_sampler_slot": "TODO",
            "sampler_abort_rec": "TODO",
            "sampler_assign": "TODO",
            "sampler_bank": "TODO",
            "sampler_color": "TODO",
            "sampler_edit": "TODO",
            "sampler_group_color": "TODO",
            "sampler_group_mute": "TODO",
            "sampler_group_name": "TODO",
            "sampler_group_volume": "TODO",
            "sampler_has_group": "TODO",
            "sampler_load_to_deck": "TODO",
            "sampler_loaded": "TODO",
            "sampler_loop": "TODO",
            "sampler_mode": "TODO\n\n-----Alias-----\nsampler_rapidfire",
            "sampler_mute": "TODO",
            "sampler_options": "TODO",
            "sampler_output": "TODO",
            "sampler_pad": "TODO",
            "sampler_pad_page": "TODO",
            "sampler_pad_shift": "TODO",
            "sampler_pad_volume": "TODO",
            "sampler_pfl": "TODO",
            "sampler_play": "TODO",
            "sampler_play_stop": "TODO",
            "sampler_play_stutter": "TODO",
            "sampler_position": "TODO",
            "sampler_rec": "TODO",
            "sampler_rec_delete": "TODO",
            "sampler_select": "TODO\n\n-----Alias-----\nsampler_default",
            "sampler_start_rec": "TODO",
            "sampler_stop": "TODO",
            "sampler_stop_rec": "TODO",
            "sampler_used": "TODO\n\n-----Alias-----\nget_sampler_used",
            "sampler_velocity": "TODO",
            "sampler_volume": "TODO",
            "sampler_volume_master": "TODO",
            "sampler_volume_nogroup": "TODO",
            "scratchbank_assign": "TODO",
            "scratchbank_edit": "TODO",
            "scratchbank_load": "TODO",
            "scratchbank_load_to_deck": "TODO",
            "scratchbank_unload": "TODO\n\n-----Alias-----\nsampler_unload_from_deck"
        },
        "sandbox":
        {
            "can_sandbox": "TODO",
            "sandbox": "TODO"
        },
        "sync":
        {
            "auto_bpm_transition": "TODO",
            "auto_bpm_transition_options": "TODO",
            "auto_sync_settings": "TODO",
            "beatlock": "TODO",
            "get_bpm_match": "TODO",
            "is_sync": "TODO",
            "match_bpm": "TODO",
            "match_gain": "TODO",
            "phrase_sync": "TODO",
            "play_onbeat": "TODO",
            "play_sync": "TODO",
            "play_sync_onbeat": "TODO\n\n-----Alias-----\nsync_nocbg",
            "quantize_all": "TODO",
            "smart_fader": "TODO",
            "sync": "TODO",
            "sync_hint": "TODO"
        },
        "text":
        {
            "countdown": "TODO",
            "get_status": "TODO",
            "get_text": "TODO",
            "stopwatch": "TODO",
            "stopwatch_reset": "TODO"
        },
        "timecode":
        {
            "get_hastimecode": "TODO",
            "get_timecode_quality": "TODO",
            "invert_timecode": "TODO",
            "timecode_active": "TODO",
            "timecode_bypass": "TODO",
            "timecode_cd_mode": "TODO",
            "timecode_config": "TODO",
            "timecode_mode": "TODO",
            "timecode_motor_enable": "TODO",
            "timecode_options": "TODO",
            "timecode_pitch": "TODO",
            "timecode_reset_pitch": "TODO"
        },
        "video":
        {
            "has_video_mix": "TODO",
            "is_audioonlyvisualisation": "TODO",
            "is_video": "TODO",
            "leftvideo": "TODO",
            "leftvideo_button": "TODO",
            "over_video": "TODO\n\n-----Alias-----\novervideo",
            "rightvideo": "TODO",
            "rightvideo_button": "TODO",
            "video": "TODO",
            "video_crossfader": "TODO",
            "video_crossfader_auto": "TODO",
            "video_crossfader_link": "TODO",
            "video_delay": "TODO",
            "video_fadetoblack": "TODO",
            "video_level": "TODO",
            "video_output": "TODO",
            "video_transition": "TODO"
        }
    }
}
